"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$git_commit\
$character"""

right_format = """
$python\
$kubernetes\
"""

add_newline = false

palette = 'campbell'

[palettes.campbell]
black = '#0C0C0C'
blue = '#0037DA'
cyan = '#3A96DD'
green = '#13A10E'
purple = '#881798'
red = '#C50F1F'
white = '#CCCCCC'
yellow = '#C19C00'


[directory]
style = "yellow"
format = "([$path ]($style))"
truncate_to_repo = true

[git_branch]
style = "cyan"
format = '([$branch ]($style))'

[git_commit]
style = "cyan"
format = '([$hash ]($style))'

[git_status]
format = '($staged$modified$ahead_behind)'
ahead = "([⇡${count} ](cyan))"
behind = "([⇣${count} ](cyan))"
modified = "([!${count} ](red))"
diverged = '([⇕ ](cyan))'
staged = "([+${count} ](green))"

[kubernetes]
disabled = false
style = 'purple'
format = "([ $context]($style))"
detect_folders = ["k8s"]
detect_files = ["skaffold.yaml"]
contexts = [
  { context_pattern = ".*production.*", context_alias = "prod" },
  { context_pattern = ".*test.*", context_alias = "test" },
]

[python]
symbol = "🐍"
format = '([ $virtualenv](green))'

[character]
disabled = false
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'
